// The corpus reports: content/corpus/index.json (every book Rafiq can draw on, wherever it lives),
// content/corpus/MANIFEST.json (counts, characters per language and failures, per source) and
// docs/COVERAGE.md (which book sections and hadith categories cover each lesson).

import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadBooks, relative } from "./books.mjs";
import { characters, corpusDir, exists, readJson, root, today, writeJson } from "./common.mjs";
import { COVERAGE_TOPICS } from "./coverage-topics.mjs";
import { BOOK_PAIRS } from "./pairs.mjs";
import { matches } from "./text-match.mjs";

/** Below this many characters of book text in a language, a lesson is flagged as thinly covered. */
const THIN = 1500;
const MCP = "https://mcp.islamiccontent.org/mcp";

async function directorySize(dir, skip = () => false) {
  let total = 0;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (skip(full)) continue;
    total += entry.isDirectory() ? await directorySize(full, skip) : (await stat(full)).size;
  }
  return total;
}

const sum = (values) => values.reduce((total, value) => total + value, 0);

export async function writeCorpusIndex() {
  const books = await loadBooks();
  const termsDir = path.join(corpusDir, "terms");
  const terms = (await exists(termsDir)) ? (await readdir(termsDir)).filter((name) => name.endsWith(".json")).sort() : [];
  const index = {
    builtOn: today,
    books: books.map((book) => ({
      id: book.id,
      language: book.language,
      title: book.title,
      url: book.url,
      path: relative(book.dir),
      stored: book.kind === "corpus" ? "content/corpus (git-ignored, rebuilt by fetch-content --corpus)" : "content/fetched (lesson evidence, kept in the repository)",
      sections: book.sections.length,
      characters: sum(book.sections.map((section) => section.characters)),
      ...(book.failures.length ? { failures: book.failures } : {}),
    })),
    pairs: BOOK_PAIRS.map((pair) => `content/corpus/books/pairs/${pair.book}.json`),
    hadithCatalogue: "content/corpus/hadith-catalogue.json",
    terms: terms.map((name) => `content/corpus/terms/${name}`),
    liveRetrieval: { url: MCP, note: "Quran and hadith texts are read live from the MCP server and never stored. See docs/MCP_TOOLS.md." },
  };
  await writeJson(path.join(corpusDir, "index.json"), index);
  return index;
}

async function lessons() {
  const dir = path.join(root, "content", "lessons", "drafts");
  const files = (await readdir(dir)).filter((name) => name.endsWith(".json"));
  const loaded = await Promise.all(files.map(async (name) => JSON.parse(await readFile(path.join(dir, name), "utf8"))));
  return loaded.sort((a, b) => a.id.localeCompare(b.id, "en", { numeric: true }));
}

function coverage(lesson, books, catalogue) {
  const topic = COVERAGE_TOPICS[lesson.id] ?? { ar: [], en: [] };
  const sections = books.flatMap((book) =>
    book.sections
      .filter((section) => (topic[book.language] ?? []).some((phrase) => matches(phrase, section.heading)))
      .map((section) => ({ book, section })),
  );
  const categories = catalogue.categories.filter(
    (category) => category.chosen && ["ar", "en"].some((language) => (topic[language] ?? []).some((phrase) => matches(phrase, category.title[language]))),
  );
  const hadithCount = (id) => catalogue.hadiths.filter((hadith) => hadith.categories.includes(id)).length;
  const charactersIn = (language) => sum(sections.filter(({ book }) => book.language === language).map(({ section }) => section.characters));
  return {
    sections,
    categories: categories.map((category) => ({ ...category, hadiths: hadithCount(category.id) })),
    characters: { ar: charactersIn("ar"), en: charactersIn("en") },
  };
}

const cell = (text) => String(text ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");

function coverageDoc(rows, books) {
  const lines = [
    "# Coverage",
    "",
    `Which stored book sections and which HadeethEnc categories cover each lesson in \`content/lessons/drafts/\`, generated by \`node scripts/fetch-content.mjs --corpus\` on ${today}. A section or category covers a lesson when its heading or title contains one of the lesson's search phrases (\`scripts/sources/coverage-topics.mjs\`), ignoring case, diacritics, tatweel and alef forms; every match is listed below so it can be checked. Characters are counted from the matched book sections' text, per language. Lessons with fewer than ${THIN.toLocaleString("en")} characters in either language are flagged. Quran and hadith texts are not counted: they are read live from the MCP server.`,
    "",
    "Books counted:",
    "",
    ...books.map((book) => `- \`${book.id}\` (${book.language}) ${book.title}: ${book.sections.length} sections${book.sections.length === 0 ? " (no text: see MANIFEST.json)" : ""}`),
    "",
    "| Lesson | Sections (ar) | Sections (en) | Characters (ar) | Characters (en) | Hadith categories (hadith titles) | Flag |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ];
  for (const { lesson, result } of rows) {
    const count = (language) => result.sections.filter(({ book }) => book.language === language).length;
    const thin = ["ar", "en"].filter((language) => result.characters[language] < THIN);
    lines.push(
      `| ${lesson.id} ${cell(lesson.title.en)} | ${count("ar")} | ${count("en")} | ${result.characters.ar.toLocaleString("en")} | ${result.characters.en.toLocaleString("en")} | ${result.categories.length} (${sum(result.categories.map((category) => category.hadiths))}) | ${thin.length ? `under ${THIN.toLocaleString("en")} (${thin.join(", ")})` : ""} |`,
    );
  }
  lines.push("", "## Details", "");
  for (const { lesson, result } of rows) {
    lines.push(`### ${lesson.id} ${lesson.title.en} · ${lesson.title.ar}`, "");
    if (result.sections.length === 0) lines.push("- Book sections: none matched.");
    for (const { book, section } of result.sections) {
      lines.push(`- \`${book.id}\` ${section.anchor} (${book.language}): ${cell(section.heading ?? "(no heading)")} · ${section.characters.toLocaleString("en")} characters`);
    }
    if (result.categories.length === 0) lines.push("- Hadith categories: none matched.");
    for (const category of result.categories) {
      lines.push(`- Category ${category.id}: ${cell(category.title.en ?? "(no English title)")} · ${cell(category.title.ar)} · ${category.hadiths} hadith titles`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export async function writeReports() {
  const books = await loadBooks();
  const catalogueFile = path.join(corpusDir, "hadith-catalogue.json");
  const catalogue = (await exists(catalogueFile)) ? await readJson(catalogueFile) : { categories: [], hadiths: [], chosenCategories: [] };
  const lastRunFile = path.join(corpusDir, ".cache", "last-run.json");
  const lastRun = (await exists(lastRunFile)) ? await readJson(lastRunFile) : {};
  const termsDir = path.join(corpusDir, "terms");
  const terms = (await exists(termsDir))
    ? await Promise.all((await readdir(termsDir)).filter((name) => name.endsWith(".json")).map((name) => readJson(path.join(termsDir, name))))
    : [];

  const byLanguage = (list, language) => sum(list.filter((book) => book.language === language).flatMap((book) => book.sections.map((section) => section.characters)));
  const corpusBooks = books.filter((book) => book.kind === "corpus");
  const islamhouse = corpusBooks.filter((book) => book.id.startsWith("islamhouse-"));
  const byenah = corpusBooks.filter((book) => book.id.startsWith("byenah-"));
  const fetched = books.filter((book) => book.kind === "fetched");
  const notesFor = async (list) => {
    const notes = [];
    for (const book of list) {
      const index = await readJson(path.join(book.dir, "index.json"));
      for (const heading of index.headingsWithoutText ?? []) notes.push(`${book.id}: heading "${heading}" has no text under it (pictures only), not saved`);
      let glyphs = 0;
      for (const section of book.sections) {
        const saved = await readJson(section.file);
        glyphs += saved.paragraphs.filter((paragraph) => paragraph.quranGlyphs).length;
        if (saved.headingFragments) notes.push(`${book.id} ${section.anchor}: heading extracted in pieces ${JSON.stringify(saved.headingFragments)}; the longest is used`);
      }
      if (glyphs) notes.push(`${book.id}: ${glyphs} pages carry Quran verses in a glyph font that does not extract as text (marked quranGlyphs)`);
    }
    return notes;
  };
  const termCharacters = (language) => sum(terms.map((term) => characters((term.languages[language]?.fields ?? []).map((field) => field.text))));

  const manifest = {
    builtOn: today,
    size: {
      corpusBytes: await directorySize(corpusDir, (file) => file.includes(`${path.sep}.cache`)),
      cacheBytes: (await exists(path.join(corpusDir, ".cache"))) ? await directorySize(path.join(corpusDir, ".cache")) : 0,
    },
    sources: {
      "byenah.com": {
        counts: { books: byenah.length, sections: sum(byenah.map((book) => book.sections.length)) },
        characters: { en: byLanguage(byenah, "en") },
        failures: lastRun.byenah ?? [],
        notes: await notesFor(byenah),
      },
      "islamhouse.com (corpus books)": {
        counts: {
          books: islamhouse.length,
          booksWithText: islamhouse.filter((book) => book.sections.length > 0).length,
          sections: sum(islamhouse.map((book) => book.sections.length)),
        },
        characters: { ar: byLanguage(islamhouse, "ar"), en: byLanguage(islamhouse, "en") },
        failures: [...new Set([...(lastRun.islamhouse ?? []), ...islamhouse.flatMap((book) => book.failures.map((failure) => `${book.id}: ${failure}`))])],
        notes: await notesFor(islamhouse),
      },
      "islamhouse.com (lesson books in content/fetched, indexed in place)": {
        counts: { books: fetched.length, sections: sum(fetched.map((book) => book.sections.length)) },
        characters: { ar: byLanguage(fetched, "ar"), en: byLanguage(fetched, "en") },
        failures: [],
      },
      "hadeethenc.com": {
        counts: {
          categories: catalogue.categories.length,
          chosenCategories: catalogue.chosenCategories.length,
          hadithTitles: catalogue.hadiths.length,
          withoutEnglishTitle: catalogue.hadiths.filter((hadith) => hadith.noEnglishTitle).length,
        },
        characters: {
          ar: characters(catalogue.hadiths.map((hadith) => hadith.title.ar ?? "")),
          en: characters(catalogue.hadiths.map((hadith) => hadith.title.en ?? "")),
        },
        failures: lastRun.hadeethenc ?? [],
      },
      "terminologyenc.com": {
        counts: { terms: terms.length, ar: terms.filter((term) => term.languages.ar).length, en: terms.filter((term) => term.languages.en).length },
        characters: { ar: termCharacters("ar"), en: termCharacters("en") },
        failures: lastRun.terminologyenc ?? [],
      },
      "mcp.islamiccontent.org": {
        counts: {},
        characters: {},
        use: "live retrieval, nothing stored (docs/MCP_TOOLS.md)",
        failures: [],
      },
    },
  };
  await writeJson(path.join(corpusDir, "MANIFEST.json"), manifest);

  const rows = (await lessons()).map((lesson) => ({ lesson, result: coverage(lesson, books, catalogue) }));
  await writeFile(path.join(root, "docs", "COVERAGE.md"), coverageDoc(rows, books));
  return manifest;
}
